name: ardour_tech_analysis
description: Lint rules for Dart and Flutter
version: 1.0.0
homepage: https://github.com/ardourtech/dart_analysis

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: '>=1.0.1 <2.0.0'
  flutter_lints: '>=1.0.0 <2.0.0'
